### ISSUE TITLE
Still Breaks New Folder and Edit Properties for Bookmarks (and Unstable Dialogs)

### ISSUE THREAD

**Issue by PowerSheetAI** [piroor/multipletab#101]
A few days ago, both Multiple Tab Handler and Tree Style Tabs broke critical functionality for Firefox Dev and Nightly. resulting in Firefox no longer showing dialogs and drop-downs, including the Firefox main app (hamburger) menu, LastPass, Add Bookmark, New Bookmark folder, and even addon install dialogs. 
Though some (not all) of the issues were fixed with a follow-up XPI release for Tree Style Tab, all those issues remain for Multiple Tab Handler.

Temporary workaround:
Add "return;" after line 25 in content\multipletab\lib\bookmarkMultipleTabs_bookmarkPropertiesOverlay.xul

However, as the use of "patching" to extend dialogs like BookmarkPropertiesDialog has broken other core functionality for Tree Style Tabs for about a year, and, even with my manually applied workaround, still more critical functionality was broken with recent Firefox updates, I would suggest:
1. Releasing an updated XPI ASAP with at least the above workaround, to restore core Firefox functionality
2. Making Add/Edit Bookmark dialog enhancements optional features that are disabled by default
3. Testing with Firefox Dev and/or Nightly editions
4. Finding a safer alternative to regex-based "patching" of dialogs like "BookmarkPropertiesDialog" (eg. injecting via DOM / inserting child elements instead) if possible

For reference, I have Firefox Developer Edition 64-bit and a Windows 10 x64 PC, and confirmed Multiple Tab Handler was the source of these issues, by reproducing the issues after disabling all other extensions and then seeing the issues resolved after disabling Multiple Tab Handler as well.

**Comment by piroor** [comment]
The commit 073912553e855e7743f1179b98069472d5c4acaf should fix this.

**Comment by labrute57** [comment]
even under offical firefox 42 and beta 43 when from the personnal bar I attempt to to go to the properties of the bookmarks I've got only a window with a combobax named parent and it
![2015-11-19 07_56_32-](https://cloud.githubusercontent.com/assets/555168/11264322/0b6809e8-8e93-11e5-9f0c-c00620652a7b.png)
 is empty

**Comment by piroor** [comment]
@labrute57 Does this still appear on the latest development build?: http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by labrute57** [comment]
I can'i install it because it is not signed

**Comment by piroor** [comment]
The signature check can be disabled by `xpinstall.signatures.required` at `about:config`. (By the way, on official Firefox 44 and later the preference is going to be unavailable, so you'll have to use a beta version, "Firefox Developer Edition", or "Nightly".)

**Comment by labrute57** [comment]
I try the nyhtly : all is looking fine now

**Comment by piroor** [comment]
Outdated.
