### ISSUE TITLE
"Invert Selection" works wrong from auto-opened menu

### ISSUE THREAD

**Issue by Infocatcher** [piroor/multipletab#103]
STR:
* hold left mouse button on some tab and select some tabs
* release mouse button (appears popup menu)
* click on "Invert Selection": selection will be cleared

Looks like this is side-effect of "Clear tab selection after the popup menu is closed" option.

**Comment by piroor** [comment]
Thanks. 1a468cb solves this.

**Comment by Infocatcher** [comment]
Thanks, now works fine.
