### ISSUE TITLE
Select Similar Tabs and Close Similar Tabs don't work

### ISSUE THREAD

**Issue by ChuckBaggett** [piroor/multipletab#105]
Right clicking a tab and clicking Select Similar Tabs doesn't do anything. Nothing gets selected. 
Same for Close Similar Tabs. 

If you select tabs by clicking and using the shift or control keys and do Close Selected Tabs, that does work. 

I will need to revert, and will go back  to  0.8.2015030601.1

This is with Firefox 40.0.3 on Windows 7 with Tab Mix Plus and Classic Theme Restorer and many other extensions installed.

**Comment by piroor** [comment]
This doesn't happen on my environment, with these versions:

 * Multiple Tab Handler 0.8.2015111200a131133
 * Tab Mix Plus 0.4.1.9
 * Classic Theme Restore 1.4.2

Both TMP and CTR are just installed and no configuration is changed. Any other trigger?

**Comment by piroor** [comment]
Outdated.
