### ISSUE TITLE
[feature request] "Open All in New Tabs" from clipboard

### ISSUE THREAD

**Issue by tyaremco** [piroor/multipletab#109]
I'd like to request a modification to the context menu item "Open All in New Tabs".  

text selected? | behavior
---------------------|------------
yes | open all URLs in selected text
no | ~~menu item hidden~~<br/>*open all URLs in clipboard text*

Opening URLs from the clipboard would be very useful when needing to open a list of URLs stored outside of the browser.

**Comment by piroor** [comment]
Currently MTH doesn't have such a menu item for the context menu on tabs. Is this a feature request for a new command for the context menu on the content area? Then, it's out of purpose of MTH. It is just an addon to operate existing tabs. I think you should request it to other projects.

**Comment by tyaremco** [comment]
My mistake!  This appears to be a special feature of Tab Utilities *but only* if MTH is also installed.  If I disable MTH I don't get the "Open All in New Tabs" menu item...strange.

**Comment by tyaremco** [comment]
Sorry, it was Text Link that is responsible for this feature.
https://github.com/piroor/textlink/issues/51
