### ISSUE TITLE
[improvement] "Open All in New Tabs" should open tabs in an unloaded state.

### ISSUE THREAD

**Issue by tyaremco** [piroor/multipletab#110]
The context menu item "Open All in New Tabs" should open tabs in an unloaded state (ie. in the same way as the Firefox option "Don't load tabs until selected").  This would greatly speed up the process of opening multiple tabs at once.

**Comment by piroor** [comment]
Is this an additional request for #109? Then, see my comment: https://github.com/piroor/multipletab/issues/109#issuecomment-160538560
