### ISSUE TITLE
FF Exit > "Save and Quit" first selection ignored

### ISSUE THREAD

**Issue by shlifs** [piroor/multipletab#111]
After upgrading to FF v43.0.2 (32-bit), I found that Exit > "Save and Quit" has to be selected twice: upon first selection in an open FF session, nothing happens; on the second selection, all tabs are closed and restored on restart (as expected).
I am using the latest Multiple Tab Handler add-on version --- v 0.8.2015113001 --- on a Windows 10 64-bit laptop. If I disable either this add-on or the Tab Mix Plus (TMP) add-on, the problem disappears (i.e., "Save and Quit" works immediately). This is  true for both the latest official version of TMP --- v0.4.2.0 --- and for the latest  development-build version --- v0.4.2.1pre.151226a1.
I also saw a review from Neon Knight, from 23 Dec 2015, on the Multiple Tab Handler FF add-on page (https://addons.mozilla.org/en-US/firefox/addon/multiple-tab-handler/) that reports a similar problem when Multiple Tab Handler is the only installed add-on, using FF v45 (32-bit) on Windows 7 64-bit.

**Comment by Siarhei-Yarkavy** [comment]
Can confirm and add one thing. When in dev edition 45FF I switch to e10s mode the issue disappears.

**Comment by piroor** [comment]
Currently Tab Mix Plus 0.5.0.0 is available. Does this still happen?

**Comment by piroor** [comment]
If this is related to TMP's custom session management, then I won't fix it and recommend you to disable it and use Firefox's built-in session management.

**Comment by piroor** [comment]
Outdated.
