### ISSUE TITLE
Close selected on MMC

### ISSUE THREAD

**Issue by mighelch** [piroor/multipletab#113]
Can you add option
close selected tabs on middle mouse clic?

**Comment by j-t-r2** [comment]
You can do that with this addon:
`https://addons.mozilla.org/cs/firefox/addon/tab-mix-plus/`

**Comment by j-t-r2** [comment]
Sorry, I read tab, not tabs. But suggested addon is very useful anyway ;-)

**Comment by piroor** [comment]
Currently I have no idea to do it safely, without breaking of other existing features...

**Comment by piroor** [comment]
Outdated.
