### ISSUE TITLE
Remove bookmarks

### ISSUE THREAD

**Issue by j-t-r2** [piroor/multipletab#114]
Hello,
I wonder if you could add option to remove selected tabs from bookmarks.
Many thanks for considering my request
j-t-r

**Comment by j-t-r2** [comment]
I have yet another request:
What about adding possibility to add selected tabs to existing folder. Not only a new one.
Thank you.

**Comment by j-t-r2** [comment]
Below is the Custom Buttons code that:
1. removes (without any confirmation) site from bookmarks by right clicking it in the address/location bar suggestions (when enabled in about:preferences#privacy)
2. removes (without any confirmation) currently active tab from bookmarks by left clicking newly added toolbar button BookmarkRemove
`var btn = this;
var PopupAutoCompleteRichResult = document.getElementById('PopupAutoCompleteRichResult');

btn.addEventListener("click", clickBtn, true);
PopupAutoCompleteRichResult.addEventListener("click", clickPopup, false);
btn.onDestroy = function() {
btn.removeEventListener("click", clickBtn, true);
PopupAutoCompleteRichResult.removeEventListener("click", clickPopup, false);
}

function clickBtn(event) {
if (event.button != 0) { return; }
event.preventDefault();

var url = gBrowser.selectedTab.linkedBrowser.currentURI.spec;
bookmarkRemove(url);
}

function clickPopup(event) {
if (event.button != 2) { return; }

var item = PopupAutoCompleteRichResult.richlistbox.getSelectedItem(0);
if (item && (item.getAttribute('type') == 'bookmark')) {
var url = item.getAttribute('url');
bookmarkRemove(url);
item.setAttribute('type', 'favicon');

var image = item.ownerDocument.getAnonymousElementByAttribute(item, 'anonid', 'type-image');
if (image) {
image.setAttribute('class', 'ac-type-icon ac-result-type-favicon');
}
var an_url = item.ownerDocument.getAnonymousElementByAttribute(item, 'anonid', 'url');
if (an_url) {
an_url.setAttribute('type', 'favicon');
}
var an_action = item.ownerDocument.getAnonymousElementByAttribute(item, 'anonid', 'action');
if (an_action) {
an_action.setAttribute('type', 'favicon');
}
}
}

function bookmarkRemove(url) {
var bmsvc = Components.classes["@mozilla.org/browser/nav-bookmarks-service;1"].getService(Components.interfaces.nsINavBookmarksService);
var ios = Components.classes["@mozilla.org/network/io-service;1"].getService(Components.interfaces.nsIIOService);
var uri = ios.newURI(url, null, null);
var bookmarksArray = bmsvc.getBookmarkIdsForURI(uri, {});
for (var i of bookmarksArray) {
bmsvc.removeItem(i);
}
}`
See:
`https://discourse.mozilla-community.org/t/remove-bookmark-with-right-click-in-location-bar-suggestions/7586`
Couldnt be function bookmarkRemove(url) somewhat implemented into your extension to remove selected tabs from bookmarks withnout any confirmation?
Or could you please at least provide me with knowledge how to localize tabs selected with your extenstion so the code above can be extended in this way?
I really appreciate any help you can provide.

**Comment by piroor** [comment]
This is done by recent commits.

**Comment by j-t-r2** [comment]
Thank you! How can I please install these latest commits -> https://github.com/piroor/multipletab/commits/master?

**Comment by piroor** [comment]
Here is development builds from latest sources. http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by j-t-r2** [comment]
Works as it should. Thanks again!
