### ISSUE TITLE
drag/drop non-adjacent tabs drops them in reverse order

### ISSUE THREAD

**Issue by stilez** [piroor/multipletab#115]
1. Installed extensions "Multiple tab handler" on a clean install of Waterfox 44 (believed to be identical behaviour to firefox 44 for this sort of thing) with no previous profile. 
2. Opened 5 tabs to random URLs (google, microsoft etc).
3. Selected tabs 3 and 5, and dragged them to between tab 3 and 4.

Expected result: 
12345 -> 12354

Actual result:
12345 -> 12534 
(the dragged tabs were dropped/inserted in reverse order)

**Comment by piroor** [comment]
This doesn't happen on my Firefox 47...

**Comment by piroor** [comment]
When tabs are wrongly rearranged in the reverse order? After dropped, or while dragged?

**Comment by piroor** [comment]
Outdated.
