### ISSUE TITLE
Cannot Move Tabs on Firefox 45

### ISSUE THREAD

**Issue by sudentor** [piroor/multipletab#116]
Starting from Firefox 45, it is no longer possible to move single or multiple tabs.

EDIT: Works again for Firefox 46.

**Comment by thaliel** [comment]
If you also use reminderfox, then it was that using the problem

**Comment by piroor** [comment]
Can I close this issue?

**Comment by malnvenshorn** [comment]
I have the same problem. If I select multiple tabs I can't move them to an existing group. I have only the option for moving them to a new group, which works. The issue occurred after switching from the build in tab groups to the addon. Currently I'm using Firefox 46.0.1. Reminderfox is not installed.

**Comment by piroor** [comment]
@malnvenshorn Is it a compatibility issue with another addon? Then I think it should be tracked as another issue, with the detailed situation.

**Comment by malnvenshorn** [comment]
I don't think so. I disabled everything, except for the tab group and multiple tab handler addon, with the same result.

**Comment by piroor** [comment]
If the problem you saw appears around a unique feature of the tab group addon, I think it is a compatibility issue with the addon, not for the Firefox itself.

**Comment by malnvenshorn** [comment]
Then it seems that your addon doesn't work with the tab group addon. With Firefox version prior to 45 where the tab groups are build into the Firefox itself I've got no problems.

**Comment by piroor** [comment]
Thanks, then is your report about "move to group" across groups, from the menu command?

**Comment by malnvenshorn** [comment]
Yes that's correct.

**Comment by piroor** [comment]
For aggregation, I mark this as a duplicated of #118 and close this.
