### ISSUE TITLE
negative influence on adblock

### ISSUE THREAD

**Issue by thaliel** [piroor/multipletab#117]
when I have MTH enabled, adblock plus will no longer be able to save or delete any filters. I might even find it completely void of filters and even lists, saying I am not subscribed to any list and have no filters, which I do. As soon as I disable MTH, everything is back to normal

**Comment by piroor** [comment]
Could you describe detailed steps how to reproduce the problem? Because I'm not familiar to ABP, I couldn't know how to do it.

**Comment by rayman89** [comment]
Are you on windows? Have you tested this on a clean profile with just ABP and MTH installed cause I can't reproduce it.

To create an other profile on windows just create a new direct link to it and on property add this to the end ( -profile "pro2/" -P "pro2" -no-remote) without the () and open it and it should be a blank new firefox (this wont delete anything so don't worry just open firefox like you normally do when you wanna use it and it will all be there).

**Comment by piroor** [comment]
Outdated.
