### ISSUE TITLE
[Conflict with Auto Unload Tabs] Reload Selected Tabs 

### ISSUE THREAD

**Issue by jmain33** [piroor/multipletab#119]
Maybe this isn't a conflict and more of an issue with unloaded tabs in general.

Selecting multiple tabs, _some of which are unloaded_, and choosing 'reload selected tabs' > the tabs reload per activity icon, but they do not load, they stay unloaded.

Selecting multiple tabs and choosing 'unload selected tabs' works fine, reloading them does not.

**Comment by piroor** [comment]
I've tried the Auto Unload Tab addon but MTH reloads unloaded tab as I expected. I tested with the steps:

 1. Install both addons.
 2. Open some tabs.
 3. Unload some tabs by AUT.
 4. Select them and try to reload by MTH.

Any other extra condition?

**Comment by jmain33** [comment]
Dug a little deeper and found this to actually be a Tab Mix Plus conflict involving customized tab styles.
When several tabs are reloaded by MTH they do indeed reload, but their styling isn't updated to reflect their new state; IE they still appear as unloaded, but when you switch to them they don't need to load again. For a single tab there is no such issue, it only arises when selecting multiple tabs.

I assume their is a conflict of some sort with the painted overlay that MTH uses. It must be blocking the TMP from repainting its styling.

**Comment by GeekUser2** [comment]
I have the same problem. Only instead of using Auto Unload Tabs I use BarTab Heavy.

**Comment by rayman89** [comment]
I use those add-ons and tried and didn't see any problem. Do you have .8.9 version of AUT? cause .8.8 was buggy on version 45+ of firefox.

Also have you checked if using classic theme restorer to change the tab appearence fixes it?

**Comment by piroor** [comment]
Outdated.
