### ISSUE TITLE
Few functions incompatible with Firefox 64bit 50.0a1 e10s, when e10s is disabled functions were back

### ISSUE THREAD

**Issue by loa11** [piroor/multipletab#122]
Few functions incompatible with Firefox 64bit 50.0a1 e10s, when e10s is disabled functions were back.

Functions like shift select multiple tabs, or ctrl + click to close tab etc...

**Comment by piroor** [comment]
Shift-click works for me on Nightly 50.0a1 (64bit) with e10s. Ctrl-click toggles the selection for me, and if I choose "Close Tab" from MTH's configuration dialog, it also works. (I didn't know now Firefox ignores ctrl-click on tabs by default - without MTH, Firefox does nothing for ctrl-click.) Any other condition, like extra addons like Tab Mix Plus?

**Comment by loa11** [comment]
Which version of multipletab do you use maybe I will have luck with same version I only need shift+ mouse left click to select multiple tabs  to be able to close selected tabs.
I bet you have your own version :)

**Comment by loa11** [comment]
Piro you are very clever guy, I know that you can find the conflict in a matter of minutes could you look where is the conflict between VTR and MTH?

Thank you.

P.S.
And please Piro don't be offended because I'm using VTR and not your Tree Style Tab.
VTR is just what I need , it leaks very little graphically and  functionally its almost perfect.
I would use your Tree Style Tab if I could configure it to be as VTR.

**Comment by piroor** [comment]
I've confirmed that MTH doesn't work with Vertical Tabs Reloaded. Thanks.

**Comment by piroor** [comment]
I've read VTR's sources. In short; VTR's implementation seems too rough as a bootstrapped (restartless) addon. It modifies DOM tree around tabs dynamically, then registered event listeners and updated functions introduced by MTH are cleared totally or partially...

**Comment by piroor** [comment]
Hmm, I misunderstood. After VTR is disabled, functions of MTH are back.

**Comment by loa11** [comment]
Piro also try start "New non-e10s window" and try VTR and MTH and you will see that they are working again both, you can select tabs with shift+click and you can ctrl+click and it will close tabs.
When you are back to pure  e10s window they are in conflict.

**Comment by loa11** [comment]
VTR is also great because it I think only tree tab addon that will work like it should in html5 full screen kiosk mode also visually you can get great look of tree, you can position tabs, it has great combination of colors for compatibility with the themes.
Personally I would like if I would get all of that from your treestyle tab :)

**Comment by piroor** [comment]
Outdated.
