### ISSUE TITLE
is it possible?

### ISSUE THREAD

**Issue by David1ali12** [piroor/multipletab#124]
is there anyway to control 2 browser tab's at the same time on a single tab show only the first thanks

**Comment by piroor** [comment]
Sadly I couldn't understand the expected behavior. Could you describe it with more details?

**Comment by rayman89** [comment]
I think he is looking for this https://addons.mozilla.org/en-US/firefox/addon/tile-tabs/

**Comment by piroor** [comment]
Outdated.
