### ISSUE TITLE
Conflict with Tab Center, can't move tabs with drag & drop

### ISSUE THREAD

**Issue by Keith94** [piroor/multipletab#126]
Tab Center extension:
https://people.mozilla.org/~bwinton/TabCenter/tab-center.xpi
https://github.com/bwinton/VerticalTabs

When both Multiple Tab Handler and Tab Center are installed, tabs can no longer be moved/re-ordered via drag and drop. Any solution to that?

**Comment by piroor** [comment]
More and more hacks are required to work MTH with Tab Center together, but currently I have less time to do that and less motivation (because I'm using my Tree Style Tab instead of Tab Center.) I need contribution from people who want to use MTH with Tab Center together.
