### ISSUE TITLE
How about adding some functionality (Rename tabs, middle click closing disable)?

### ISSUE THREAD

**Issue by wallofbytes** [piroor/multipletab#127]
Do you still develop multiple tab handler?
Subj. These functions can be realized, the first added to Tab Min Plus and the second to special addon. Can you import these fuctions to your addon? I guess, these will very useful!

**Comment by piroor** [comment]
I believe that those features don't match to the core concept of this addon: this MTH should provide ability to apply Firefox's (or other addon's) feature for multiple selected tabs, not only to the current tab. If you point something other addon which provide the feature you want, then I possibly add a new menu item like "rename these tabs" for the combination with the addon.

**Comment by wallofbytes** [comment]
Sorry, i think i don't understand you.
> If you point something other addon which provide the feature you want, then I possibly add a new menu item like "rename these tabs" for the combination with the addon.
This functionality may be realized as changing page title. For example, 
https://addons.mozilla.org/En-us/firefox/addon/rename-tab-title/
https://addons.mozilla.org/En-us/firefox/addon/tabrenamizer/
allow to rename tabs (in current session). And TabMixPlus allows to rename (each, not only groups) tab's name (regardless of the session).

**Comment by piroor** [comment]
OK, then I can add menus for the feature for MTH.

However, now I have a question. Do you actually need "rename selected tabs" feature, not "rename this tab"? If not - if you just want to change the title of the current tab without any addon, then you just have to create a bookmark with the URL `javascript:(function(){document.title=prompt()})()`.

**Comment by piroor** [comment]
Outdated.
