### ISSUE TITLE
Drag and drop multiple selected tabs to empty space does not move them all to the new window since Firefox 47+

### ISSUE THREAD

**Issue by Rikk** [piroor/multipletab#129]
This started again with Firefox 47.
It is the same I reported last year: https://github.com/piroor/multipletab/issues/88

Drag and drop multiple selected tabs to empty space does not move them all to the new window since Firefox 47. Menu "Move to new window" is working normally.

1. Select 2 or more tabs.
2. Drag and drop them over any empty space in the current page.
3. Only one of the selected pages will move to a new window.

**Comment by piroor** [comment]
Thanks! The commit fd8ae679c974d8f07e04f6d61518ae06be8c9375 fixes it.

**Comment by Rikk** [comment]
Thanks.
I'm happy to see you actively working in MTH again.
