### ISSUE TITLE
Drag and drop of tabs always selects and loads the 1st selected tab

### ISSUE THREAD

**Issue by arni2033** [piroor/multipletab#130]
My Info:   Win7_64, Nightly 49, 32bit, ID 20160526082509 (2016-05-26)

STR_1:
1. Open new window, open https://www.youtube.com/watch?v=mD3v1B_aXw0 in a new tab, close other tabs.
2. Open 2 new tabs (Ctrl+T, Ctrl+T). Close and restore that window
3. Click on the 2nd tab, hold Shift, click on the 1st tab (to select first 2 tabs)
4. Hover mouse over the 2nd tab, hold left mouse button, drag and drop tabs to the end of tabs strip

AR:
 Youtube tab BECOMES SELECTED and loads, unwanted sound appears. Browser consumes more RAM
 Also it is just distracting and I may accidentally loose originally selected tab
ER:
 Selected tab should stay selected when I drag it.
 Other tabs (e.g. 1st selected tab) shouldn't become selected

**Comment by piroor** [comment]
Outdated.
