### ISSUE TITLE
Tab Groups extension: selected tabs change their order if I drag and drop them

### ISSUE THREAD

**Issue by arni2033** [piroor/multipletab#131]
My Info:   Win7_64, Nightly 49, 32bit, ID 20160526082509 (2016-05-26)

STR_1:
0. Install https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/
1. Open new window, create new tab group, create 1 tab in that group, select that tab
2. Load "data:,1" in the only tab. Open "data:,2" in a new tab. Open "data:,3" in a new tab
3. Click on the 1st tab, hold Shift, click on the 2nd tab (to select first 2 tabs)
4. Hover mouse over the 2nd tab, hold left mouse button, drag and drop tabs to the end of tabs strip

AR:
 Selected tabs change their order:    "data:,3", "data:,2", "data:,1"  (last 2 tabs are selected)
ER:
 Selected tabs should preserve order: "data:,3", "data:,1", "data:,2"  (last 2 tabs are selected)

**Comment by piroor** [comment]
I couldn’t reproduce this problem with the combination:

 * Nightly 52.0a1/20161103030205
 * Multiple Tab Handler 0.8.2016110400a183000 (latest development build)
 * Tab Groups 2.1

Could you retry with latest versions?

**Comment by piroor** [comment]
Outdated.
