### ISSUE TITLE
Selected background tabs twitch when I drag tabs

### ISSUE THREAD

**Issue by arni2033** [piroor/multipletab#133]
My Info:   Win7_64, Nightly 49, 32bit, ID 20160526082509 (2016-05-26)

STR_1:
1. Open new window, open 10 tabs in that window
2. Select the last 2 tabs
3. Start dragging the 9th tab to the left

AR:  10th tab constantly twitches to left and right
ER:  10th tab should move smoothly

**Comment by piroor** [comment]
Sadly it is a limitation - not a designed but an unavoidable behavior. By some reasons, I had to give up to move those tabs completely together.

**Comment by piroor** [comment]
Outdated.
