### ISSUE TITLE
Drag and drop doesn't move selected pending tabs to another window in some cases

### ISSUE THREAD

**Issue by arni2033** [piroor/multipletab#134]
My Info:   Win7_64, Nightly 49, 32bit, ID 20160526082509 (2016-05-26)

STR_1:
1. Open new window with about:home (Ctrl+N)
2. Open new window, open new tab (Ctrl+T), close that window, restore that window
3. Open new tab (Ctrl+T), move it to the left to make it the 1st tab
4. Hold Shift, click on the last tab (to select all tabs)
5. Hover mouse over the 1st tab, start drag-n-drop
6. Switch to the window from Step 1 (Alt+Tab), drop tabs after the only tab

AR:
 3 new tabs appear in the window from Step 1:  "about:newtab", "about:blank", "about:blank"
 about:home and about:newtab from window from Step 2 aren't moved to window from Step 1
ER:
 All selected tab should be moved from window from Step 2 to window from Step 1.
 (One about:newtab tab should stay if you wish so - still acceptable, and may be useful)

STR_2:  (original)
1. Open new window with about:home (Ctrl+N)
2. Open new window, open exactly 4 tabs in that window: "data:,1", "data:,2", "data:,3", "data:,4"
   open new tab (Ctrl+T), close that window, restore that window
3. Open new tab (Ctrl+T), move it to the left to make it the 1st tab
4. Hold Shift, click on the last tab (to select all tabs)
5. Hover mouse over the 1st tab, start drag-n-drop
6. Switch to the window from Step 1 (Alt+Tab), drop tabs after the only tab

AR:
 6 new tabs appear in the window from Step 1:  "about:newtab", "about:blank", "about:blank", "about:blank", "about:blank", "about:blank"
 All tabs in window from Step 2 stay in that window, except for the 1st tab
ER:
 All selected tab should be moved from window from Step 2 to window from Step 1.
 (One about:newtab tab should stay if you wish so - still acceptable, and may be useful)

**Comment by piroor** [comment]
Outdated.
