### ISSUE TITLE
Don't focus new duplicate tabs

### ISSUE THREAD

**Issue by Keith94** [piroor/multipletab#137]
When duplicating the current tab from the context menu, the new duplicate tab opens in the foreground rather than the background. Can you add an option to always open in the background instead? Thanks.

**Comment by piroor** [comment]
By recent commits, now tabs are duplicated in the background if you Shift-Click or Middle-Click on the menu item in the context menu. But there still be no preference to apply the behavior by default. Does it help you?

**Comment by Keith94** [comment]
Thanks, the middle-click behavior is helpful.

Another thing, when duplicating multiple tabs, they might be duplicated in the wrong order. Can you check?
