### ISSUE TITLE
[New feature] Close already bookmarked

### ISSUE THREAD

**Issue by guilhas** [piroor/multipletab#140]
Hello,

Would it be possible to implement something like #114, but instead of removing bookmarks, close open tabs that are bookmark.

It can be added as optional in 'Tab Selection Menu'.

Best regards,
Lino

**Comment by piroor** [comment]
Now Firefox has tab multiselection feature, so I think it should be provided as a separate addon for the purpose. Currently MTH is an addon just provides a UI to select tabs by dragging.
