### ISSUE TITLE
Tabs selected look too "squared" / Request to change style

### ISSUE THREAD

**Issue by alex9099** [piroor/multipletab#142]
Hi, is it possible to change the style/colour of the selected tabs? 

I already searched on the source code but i cant find anything relevant :/

**Comment by piroor** [comment]
https://github.com/piroor/multipletab/blob/master/skin/classic/multipletab/multipletab.css#L3 ?

**Comment by alex9099** [comment]
Maybe a noob question :D 
on: 

`background-color: Highlight;`

Highlight is a colour? Also how can i make the borders round? only the bottom borders of the selected tab are visible, the other tabs are just solid blue :(

**Comment by piroor** [comment]
`Highlight` is one of system colors defined in CSS spec. Rounded borders are produced by `border-radius`. I think you need to learm more about CSS basic techniques and try to apply CSS rules dynamically via the browser toolbox ;)
https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox

**Comment by alex9099** [comment]
ok, thanks, i'll learn more CSS, i'll close this issue for now
