### ISSUE TITLE
Add config to move to beginning of group

### ISSUE THREAD

**Issue by cipri-tom** [piroor/multipletab#143]
Hi,
Thanks for this amazing add-on! Really time-saving !
I wanted to try and contribute back with an idea: add a config which changes the moving of tabs to other groups such that they are moved to the beginning of the group. Or maybe a menu entry (though I think a config is enough).

Many thanks!

**Comment by piroor** [comment]
Now Firefox has tab multiselection feature, so I think it should be provided as a separate addon for the purpose. Currently MTH is an addon just provides a UI to select tabs by dragging.

**Comment by cipri-tom** [comment]
My god, this is from the days when FF still had tab groups. I had no idea about TST back then, which I am using now and is saving all the trouble.

Thanks for your sustained work !
