### ISSUE TITLE
Incompatibility with Tab Mix Plus different tabs width

### ISSUE THREAD

**Issue by onemen** [piroor/multipletab#144]
When Tab mix feature 'Tab width fits to tab title' is enabled, tab move on single row is not smooth

MTH is not take into consideration different tab width, so the background tab is not moving when the dragged tab pass its center.

If you can fix this issue, i can turn off Tab mix's implementation of gBrowser.tabContainer._animateTabMove when MTH is installed

**Comment by piroor** [comment]
Thanks, confirmed with this condition:

 * tabs => [A:long long long][B:short][C:long long long][D:short]
 * operation => select C and D, and drag C at the position of A, through B

However currently I have no idea to fix this smartly...

**Comment by piroor** [comment]
Outdated.
