### ISSUE TITLE
Copy URI & Copy URI of All Tabs, non-functional in FF Developer 52-53

### ISSUE THREAD

**Issue by CrashNBurn71** [piroor/multipletab#145]
Using "Copy URI", "Copy URI of All Tabs", or "Copy URIs of Selected Tabs"  appears to put line-breaks into the clipboard ... but not much else. No obvious errors showing up in the Browser Console.

Currently the most recent Firefox Developer 53.

**Comment by akawaguc** [comment]
I also have the same issue. "Copy *" features don't work on Firefox Developer Edition 53.

**Comment by StarWeaver** [comment]
Also having this issue for a bit, also getting linebreaks in the clipboard. I am also using it with treestyle tabs. Currently firefox version 54.0a2 (2017-03-11) (32-bit)

**Comment by yuchen-lea** [comment]
Same issue:
- Multiple Tab Handler 0.8.2016111701
- firefox version 53.0a2 (64-bit)

**Comment by piroor** [comment]
Fixed by 3ed44b0b3a5d4822574a2b4445dca03ee861b8ee
