### ISSUE TITLE
Firefox 52 native 'drag-and-drop of multiple files' not working with MTH active

### ISSUE THREAD

**Issue by Rikk** [piroor/multipletab#146]
It seems that the new native '[drag-and-drop of multiple files](https://bugzilla.mozilla.org/show_bug.cgi?id=92737)' is not working in Firefox 52 when Multiple Tab Handler is enabled; works ok when I disable it.

What happens in FF 52+MTH:
![dnd-multiple-mth-ff52-bug](https://cloud.githubusercontent.com/assets/2916485/23935852/5ca59346-092d-11e7-82cc-33a5698c3fd7.png)

What should happen:
![dnd-multiple](https://cloud.githubusercontent.com/assets/2916485/23935851/5a21fc5e-092d-11e7-8f55-c8121cd17741.png)

**Comment by piroor** [comment]
Thanks a lot!

**Comment by Rikk** [comment]
@piroor Thank you!
