### ISSUE TITLE
Multiple Tab Handler not working in Firefox 53.0 under Windows 10

### ISSUE THREAD

**Issue by DavidMcRitchie** [piroor/multipletab#151]
Menus Okay, but not putting anything into the clipboard when attempting to copy multiple tabs.
Worked in 51.0.2.    Not working in 53.0.

**Comment by AnselmD** [comment]
Works in 52.0 but not in 53.0 (Windows 7)

**Comment by piroor** [comment]
It has been fixed but not released yet, sorry. See also #145 and #150.

**Comment by AnselmD** [comment]
During the time it is not released, I use the following workaround:

Multiple Tab Handler :: Reviews :: Add-ons for Firefox
https://addons.mozilla.org/en-US/firefox/addon/multiple-tab-handler/reviews/872198/

**Comment by DavidMcRitchie** [comment]
Thanks AnselmD and glad Richard Thiessen's  solution was posted in MTH reviews which is where most people check first.  Funny thing is that I already had that variable and it was set to True so set it to False then updated again to 53.0.2  it worked and changed variable back to True and MTH still worked
