### ISSUE TITLE
Copy URIs of Selected Tabs puts blank lines on clipboard

### ISSUE THREAD

**Issue by Secret-Code** [piroor/multipletab#152]
When I use menu item 'Copy URIs of Selected Tabs', blank lines are put on the clipboard, with no title or URI or anything. The number of blank lines matches the number of tabs selected. This is the same whichever option I select from the submenu, or if I set it not to show a submenu.

This used to work, but I can't be sure how recently I've tried it. Tried now in multiple Firefox profiles including with few other add-ons. Copy actions from other Firefox extensions do work. 

MTH 0.8.2016111701 (the latest from amo). 
Firefox 53.0.2 (64-bit) on Linux Kubuntu 14.04.

**Comment by AnselmD** [comment]
Hi,
see #151

**Comment by Secret-Code** [comment]
Thanks! I did search existing issues and didn't see any match. (Must have only searched open issues?) 

The workaround you (AnselmD) posted in that issue works for me.
