### ISSUE TITLE
Broken on Nightly 57.0a1 (2017-08-04) (64-bit)

### ISSUE THREAD

**Issue by tps125** [piroor/multipletab#155]
Seems to be broken with the current nightly: 57.0a1 (2017-08-04) (64-bit)
When I try to select multiple tabs, I get the default Firefox behavior of switching tabs.

**Comment by piroor** [comment]
Similar to https://github.com/piroor/treestyletab/issues/1304 and recent commits should fix this problem partially. However I've confirmed that still there are some problems...

**Comment by Vednier** [comment]
Similar (to some point) addon called All Tabs Helper also was broken 2017-08-04 and fixed by its developer. But just on 2017-08-08\09 it was broken again by changes in Nightly. So, it may be not that easy :(
Personally i hope it will be fixed, default Firefox tab handling is just atrocious.

**Comment by Vednier** [comment]
I guess it should be closed since old good XUL extension is dead

**Comment by piroor** [comment]
Outdated.
