### ISSUE TITLE
Copy URIs of Selected Tabs is breaking for large numbers of tabs

### ISSUE THREAD

**Issue by joshgold22** [piroor/multipletab#157]
After the most recent Firefox update (I'm now at 55.0.2), Copy URIs of Selected Tabs will do nothing (even when I wait minutes) if I have a lot of tabs selected.  The problem is coming up with around 100-150 tabs, whereas I used to be able to copy 3-400 with no problems besides a several-second delay.  When it works, copying fewer tabs, I don't see any noticeable slowdown compared to before. 

Note, after an earlier update I applied the following fix (from a May 12, 2017 review comment on addons.mozilla.org.)  This fixed a problem where Copy URIs didn't work at all, so I'm dealing with a different issue.

> firefox 53.x no longer has the http://kb.mozillazine.org/Network.standard-url.escape-utf8 flag which is read by documentToCopyText.js(line:75)
> 
> To fix this go to about:config
> rightclick --> new -->boolean
> set the name to: "network.standard-url.escape-utf8" (without quotes)
> set the value to True. This will disable decoding of the URIs in the add-on. If your copied URIs don't look right, try setting the value to False which should fix it.

**Comment by sw360cab** [comment]
+1 

with FF 55.x even the cited work around is not having any effect on "Copy&Paste" for multiple tabs.

**Comment by joshgold22** [comment]
I've discovered that the problem may not be the number of tabs selected.  Instead it may be a particular kind of tab that can break the whole process.

I saw the copy operation fail when I had a smaller number of tabs selected and did a search to see if one tab was breaking it.  It turned out to break on a tab like the following, generated from LeechBlock:

chrome://leechblock/content/blocked.xhtml?1&https://www.nytimes.com/

I have not tried other special tabs (like about:config.)  This definitely used to work before, and in the past I relied on it to quickly collect a list of articles to read later.  (the leechblock link contains the real link.)

I should say, this problem is showing up *after* I'd already put in the workaround above, so I apologize if I'm combining two separate issues.

**Comment by sw360cab** [comment]
I used this feature a lot.
In the past it has broken but applying the workaround (you pointed out too), it was solved.

Now with FF > 55.x it stopped working again, neither the workaroud is useful anymore.

**Comment by vonHabsi** [comment]
I am facing the same issue on Firefox 63 beta.

Is there some way to debug the addon, or trace the execution to see where it is failing?

**Comment by piroor** [comment]
The feature is now provided in a separate addon: Copy Selected Tabs to Clipboard.
