### ISSUE TITLE
Inability to select discontiguous tabs in new (WE) version

### ISSUE THREAD

**Issue by lewallen** [piroor/multipletab#162]
In the old (pre-WE) version of multiple tabs, I was able to use command-click (on a Mac) to select and deselect an arbitrary set of tabs, one by one (so in particular, the selected tabs could be discontiguous in the tree structure). Is this feature intended to be supported in the new WE version? It does not seem to work with my set up (current nightly version, info below). Currently, I can only select tabs using shift-click or hold-and-drag (and in both cases selected tabs must be continguous, as would have been the case in the older version as well, with these selection methods).

Setup:
- FF: 58.0a1 (2017-10-12) (64-bit)
- MT: Multiple Tab Handler 2.0 (updated 10/12/2017)

I would highly advocate for this feature if it is not currently implemented (and if it is technically possible with WE's) -- it was very useful (e.g., it enabled pruning a large set of tabs by selecting a subset which could then be moved together to a new window).

Thanks!

**Comment by piroor** [comment]
Did you talk about operations in the toolbar panel? Then it is my mistake sorry. Because I mainly use this with TST I forgot to implement this behavior for the panel. Now Ctrl(Command)/Shift-Click on the panel works correctly on MTH 2.0.2.

**Comment by lewallen** [comment]
Hi piroor, I am using TST as well, I'm talking about in the sidebar, is that the panel (or do you mean the "original" tabs from FF? I have those hidden). Anyway I'll check if command-click works for me in the new version. Thanks!

**Comment by piroor** [comment]
Yes I forgot to support Command-Click for macOS. This improvement on MTH 2.0.2 should work on TST's sidebar also.

**Comment by lewallen** [comment]
Sorry for continuing to bother but I installed 2.02, but Command-Click continues not to work for me. Maybe there is something strange about my setup?

**Comment by piroor** [comment]
Hmm, currently I cannot verify actual behavior on macOS. I'll try to test latest MTH on someone's MacBook.

**Comment by piroor** [comment]
After I researched I realized that i tried to detect macOS in wrong way. Now MTH 2.0.3 is available with a fix about this problem. Thankyou for a report!
