### ISSUE TITLE
Multiple Tab Handler 2.x with Firefox 56.x

### ISSUE THREAD

**Issue by grahamperrin** [piroor/multipletab#166]
> … [WebExtensions-based version is available](https://github.com/piroor/multipletab/issues/154#issuecomment-337171147) …

I understand that the minimum (but not strict) requirement for 2.x is Firefox 57.0a1. 

Please: which features might you expect to _not_ work in a 56.x environment? 

(Background: 0.8.2017061501 is simply incompatible with my preferred set of extensions for 56.)

**Comment by piroor** [comment]
Because Fx56 is now out of date, I won't do any research about Fx56. Sorry.
