### ISSUE TITLE
Higlight selected tabs

### ISSUE THREAD

**Issue by thaliel** [piroor/multipletab#167]
I have always enjoyed the visuality of tabs that I selected being highlightes in the tab bar itself. If possible, please have that return

**Comment by piroor** [comment]
Sadly there is no API to do it in WebExtensions.

**Comment by thaliel** [comment]
thankfully I haven't updated to quanum yet. Pity, though, as it was easy to see which tabs have been selected

**Comment by piroor** [comment]
Now Firefox itself has tab mutiselection feature.
