### ISSUE TITLE
Right click

### ISSUE THREAD

**Issue by rayman89** [piroor/multipletab#170]
Now if you right click without a tab selected a grey box appears without any menu items. Would it be possible to display the menu when you right click over a non selected tab name with the options applying to that tab and either make the minimum size of the  "window" that appears when you click the extension button be smaller so there is never a white space or not show the menu when you right click on a white space?

**Comment by piroor** [comment]
![image](https://user-images.githubusercontent.com/70062/33434726-74a6663c-d623-11e7-8c97-bbf52acffc87.png)

By recent commits now the menu has became more menu-like.
