### ISSUE TITLE
"Bookmark tabs" duplicates tabs and "Move tabs to new window" closes tabs

### ISSUE THREAD

**Issue by talia-storymaker** [piroor/multipletab#173]
This is my first time reporting an issue to GitHub, so forgive me if I made any mistakes, or if this isn't the right place to put this to begin with.

I am encountering a very strange error in Multiple Tabs Handler in Firefox 57 Beta. Choosing the option to bookmark tabs just causes them to be duplicated rather than bookmarked, and choosing to move them to a new window simply closes them. The other functions work just fine. I tried disabling all my other add-ons, but the problem still happens. There has never been a time for me when these two functions have worked properly.

If needed, all my Firefox information from about:support can be found [here](https://pastebin.com/A89gJ3s0). I am using Windows 10.

**Comment by eberhardweber** [comment]
Can confirm both issues on MTH 2.0.3 FF57 64-bit Windows final! Bookmarking duplicates and moving closes tabs.

**Comment by piroor** [comment]
Sorry, they were not implemented yet and wrongly fallback to other existing command. By recent commit the wrong fallback is fixed, but they are still not implemented.

**Comment by piroor** [comment]
Now both commands are implemented.

**Comment by talia-storymaker** [comment]
Excellent!! Works just as it should now. Thank you!
