### ISSUE TITLE
Move to an existing window

### ISSUE THREAD

**Issue by rayman89** [piroor/multipletab#176]
Could you make it able to move selected tabs to an existing window? Windows can be named after the current tab on each window.

**Comment by eberhardweber** [comment]
Would be a great feature. Should it be called "merging" windows?

**Comment by rayman89** [comment]
No merging would be fusing 2 windows into 1 this only moves part of one window to an other window

**Comment by piroor** [comment]
Implemented by recent commits.

**Comment by piroor** [comment]
Because I hope that the original reporter close the issue after he confirmed that it is certainly fixed, with a new release or a development build. When I close an issue by myself and it is actually not fixed on the reporter's environment, he cannot reopen the issue by his own permission.

**Comment by rayman89** [comment]
Ok then I'll close it because it's working properly. Thanks again.
