### ISSUE TITLE
TST Selection not cleared with left click on highlighted tabs

### ISSUE THREAD

**Issue by Lej77** [piroor/multipletab#180]
## Short description
Tab selection can't be cleared with left click if clicking on a selected tab. This isn't how selection works in for example Windows File Explorer. 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install MTH.
 3. Install TST.
 4. Open a couple of tabs.
 5. Select a couple of tabs.
 6. Left click on a highlighted tab.

## Expected result
All tabs should be deselected.

## Actual result
Selected tabs remain selected.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 57
 * Version (or revision) of Multiple Tab Handler: 2.0.4

**Comment by piroor** [comment]
Thanks. ea0399f should fix this.
