### ISSUE TITLE
Pop up menu suspends with many tabs

### ISSUE THREAD

**Issue by vstepaniuk** [piroor/multipletab#184]
## Short description
It takes about a minute for a pop up menu to get responsive, with around 300 tabs opened.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install MTH.
 3. Press Ctrl+T 300 times
 4. Open the MTH pop up menu

## Expected result
The menu gets responsive immediately - one can select tabs and perform any actions.

## Actual result
The menu is unresponsive for about 1 minute - one cannot select tabs and perform any actions.

## Environment

 * Platform (OS): Ubuntu 17.10 x64
 * Version of Firefox: 57.0.1 (64-bit)
 * Version (or revision) of Multiple Tab Handler: 2.0.5

**Comment by piroor** [comment]
Thanks. I've realized that loading of favicons causes the problem. By recent commits the process become progressive and the popup now appears immediately for me.
