### ISSUE TITLE
Long press on tab automatically opens TST context menu.

### ISSUE THREAD

**Issue by sumyungguy** [piroor/multipletab#189]
## Short description
With Multiple Tab Handler and Tree Style Tab installed, a long press on a tab in the TST sidebar causes the TST context menu to appear immediately. This means that after selecting multiple tabs by long press then dragging, it's not possible to move them by drag-and-drop.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install MTH.
 3. Install TST.
 4. Long press on a tab in the TST sidebar, and drag to select multiple tabs.

## Expected result
The same as with shift-selecting multiple tabs. The user can either drag-and-drop the selected tabs, or use right-click to call up the context menu.

## Actual result
The context menu is called up automatically. It's not possible to dismiss it without deselecting the tabs. It's not possible to drag-and-drop tabs. With MTH not installed, the context menu is not called up by a long press.

## Environment

 * Platform (OS): macOS 10.12.6
 * Version of Firefox: 59.0b5
 * Version (or revision) of Multiple Tab Handler: 2.0.6
 * Version of Tree Style Tab: 2.4.7

**Comment by piroor** [comment]
It is a behavior inherited from legacy version of Multiple Tab Handler so it's not a bug, but I forgot to migrate any option to deactivate this behavior. Sorry.
