### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by Empatojayos** [piroor/multipletab#19]
I love the "duplicate tab" add-on, a abandoned plug-in develoved in 2007. It's a very simple add-on, their few characteristics already are including in "Multiple Tab Handler", except the duplicate-tab icon relocatable in the navegation bar. This icon is vital for me.
Can yours integrate an icon that allows the same?
I would change of  addon and recommend it.
Thanks for its attention.

**Comment by piroor** [comment]
Outdated.
