### ISSUE TITLE
Flickering when dragging to select tabs in the TST Sidebar

### ISSUE THREAD

**Issue by Lej77** [piroor/multipletab#194]
## Short description
Selecting tabs in the TST Sidebar by holding on a tab and dragging seems to cause the selection to flicker while moving the mouse. This looks a bit bad so it would be nice if it could be fixed.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install MTH.
 3. Install TST.
 4. Press and hold the left mouse button on a tab in the TST Sidebar to start selecting tabs.
 5. Move the mouse up and down in the sidebar to change the selected tabs.

## Expected result
The selection changes should be smooth and without flicker.

## Actual result
The selected flickers when it is changing. It looks like the selection is cleared and then set again every time the selection is changed.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 59.0.2
 * Version (or revision) of Multiple Tab Handler: 2.0.10

**Comment by piroor** [comment]
Thanks, the commit 3aa6920 should fix this problem.

**Comment by Lej77** [comment]
Great!
