### ISSUE TITLE
Whitespace around ampersand in messages.json disappears

### ISSUE THREAD

**Issue by ConorAAG** [piroor/multipletab#195]
## Short description
When right-clicking on tab selection any menu item label containing ampersand that is immediately preceded/followed by a whitespace, has that whitespace stripped out. e.g. "Move Tabs to New &Window" is show in browser as "Move Tabs to NewWindow"

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install MTH.
 3. Open at least one tab
 4. Click on MTH icon
 5. Select tab and right-click on the tab entry
 6. View menu item labels. White space is missing in certain entries. In each case the missing white space is either immediately preceded or followed by an ampersand in the messages.json locale file.

## Actual result
![multitaberrorlocale](https://user-images.githubusercontent.com/36917128/39052770-ffdaab1a-44a4-11e8-862d-b52542e57fc4.png)

See above image for issue. Effected labels are:

Move to NewWindow
CopyTo Clipboard
SelectAll

## Environment

 * Platform (OS): Fedora
 * Version of Firefox: 60.0b13 (64-bit) Developer Edition
 * Version (or revision) of Multiple Tab Handler: 2.0.10

P.S. you have a typo in template for this page!!

strucutre => structure

**Comment by piroor** [comment]
After I inspected, I've confirmed that there is actually a space as: `Move Tabs to New <span class="accesskey">W</span>indow`. So, it seems to be collapsed by something CSS rule. And finally I've realized that `diplay:flex` causes this problem and it should be fixed by the commit ed97742. Thanks!

**Comment by ConorAAG** [comment]
Good stuff!
