### ISSUE TITLE
"Selected Tabs" menu item does not appear when opening menu immediately after selecting tabs

### ISSUE THREAD

**Issue by mkfmnn** [piroor/multipletab#199]
## Short description

When the user selects a range of tabs in Tree Style Tabs, and then *immediately* opens the context menu via right-click or (on Mac) control-click, the "Selected Tabs" menu item provided by Multiple Tab Handler does not appear.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST and MTH.
 3. Open 3+ tabs.
 4. Press "shift" and click another tab to select a range of tabs.
 5. **Quickly** release shift and right click the current tab to show the tab action context menu. (Within approximately 0.25 seconds of completing the previous step)

## Expected result

The context menu that is shown should contain the "Selected Tabs" menu item.

## Actual result

The item does not appear.

## Additional Information

I'm not sure what the exact threshold is. If I wait about half a second after selecting the tabs before opening the context menu, then "Selected Tabs" more reliably appears. Also, it will show up if I dismiss the menu and re-open it with another right-click.

## Environment

 * Platform (OS): macOS 10.11.6
 * Version of Firefox: 60.0.1 (64-bit)
 * Version (or revision) of Multiple Tab Handler: 2.0.12 (w/ TST 2.4.21)

**Comment by piroor** [comment]
This is a problem of TST itself. As a workaround, I've introduced some changes to TST so now TST reopens the menu automatically if any item is added or removed when the menu is already open. How about this?

**Comment by mkfmnn** [comment]
Thanks for the quick fix! So far this seems to be working well enough. The flicker as the menu reopens is a little bit disconcerting but it's definitely tolerable and far better than being confused about the item being entirely missing. Thanks again!
