### ISSUE TITLE
[API Issue] registered addons aren't cached

### ISSUE THREAD

**Issue by Lej77** [piroor/multipletab#200]
## Short description
When MTH is restarted it is supposed to remember the addons that were registered to it and send a "ready" message to them so they can register again. The setting variable `cachedExternalAddons` is used to store these values. From my testing it seems that this variable isn't saved between restarts. I did some testing and using `JSON.parse` before saving the data and `JSON.stringify` after loading it seems to fix it, so the issue seems to be that settings that are objects aren't saved between restarts.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install MTH.
 3. Add a context menu item to MTH via the API.
 4. Restart MTH.

## Expected result
The extension that registered the context menu item should be sent the "ready" message.

## Actual result
No message is sent to the extension that registered the context menu item and therefore the custom context menu item is missing after MTH is restarted.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: Firefox 60.0.1
 * Version (or revision) of Multiple Tab Handler: 2.0.12

**Comment by Lej77** [comment]
I just released my extension [Bookmark Tree for Tree Style Tab](https://addons.mozilla.org/firefox/addon/bookmark-tree-for-tst/) that adds a context menu item to MTH. It can be used to test if API extensions are cached.
### Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install MTH.
 3. Install [Bookmark Tree for Tree Style Tab](https://addons.mozilla.org/firefox/addon/bookmark-tree-for-tst/).
 4. Restart MTH.

### Expected result
Context menu item is still in MTH.

### Actual result
Context menu item is missing.

**Comment by piroor** [comment]
Thanks a lot, I forgot to do correct method to update non-primitive configuration values. The commit e8c070c should fix this problem.
