### ISSUE TITLE
Standard behavior for shift-click

### ISSUE THREAD

**Issue by joshgold22** [piroor/multipletab#203]
## Short description

Shift click currently selects all tabs from the current tab to the clicked location.  It should select tabs from the last-selected tab (e.g., with cmd-click) to the clicked location.  This is the standard behavior I've come to expect in multiple-selection interfaces, and without it it is very hard to select several disjunct sets of tabs.  (If you want to keep the selections you've already made, you must select any new groups one-by-one.)

## Steps to reproduce

1. Open tabs 1 through 20.

2. Click tab 15, making that the current tab (shown in the browser window)

3. Command-click on tabs (in this order): 17, 18, 15 (to deselect), 12, 10

4. Shift-click on tab 8

## Expected result

Selection should be 8-10,   12,  17,18

## Actual result

Selection is 8-15

(I included 17 and 18 in order to test that 16, 17 and 18 are handled correctly in the current version of MTH: 16 should stay unselected and 17 and 18 should not be deselected.  In one of my tests, 17 and 18 stayed selected, but usually they get unselected.  I haven't figured out what I did differently.)

## Environment

 * Platform (OS): OSX 10.12.6
 * Version of Firefox: 60.0.2
 * Version (or revision) of Multiple Tab Handler: 2.0.13

**Comment by piroor** [comment]
By recent commits, now any selection must include the active tab. In other words, if you unselect the active tab and there is any rest selected tab, then one of them is activated. This behavior respects the one of Firefox 63's native multiselection and Google Chrome's one. As a part of this change, the last ctrl-clicked tab is treated as the anchor for Shift-click selection.

**Comment by piroor** [comment]
TST and MTH respects selection behavior of Firefox's native tab bar itself. On that case you need to do:

 1. Ctrl(Command on macOS)-Click 1, 2, 3 and 5.
 2. Ctrl-Shift-Click on 7.

Then you'll see multiselected tabs: 1, 2, 3, 5, 6 and 7. Please note that you need to do Ctrl-Shift-Click instead of Shift-Click. On my environment, these steps produces same result on TST's sidebar and Firefox's native tab bar.
