### ISSUE TITLE
Multiple Tab Handler clutters up Browser Console with spurious errors

### ISSUE THREAD

**Issue by ssokolow** [piroor/multipletab#204]
## Short description

Multiple Tab Handler performs two different fallible `browser.runtime.sendMessage` calls without silencing the errors they may return under normal operation.

This adds extra clutter to the Browser Console which reduces its utility.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Open the Browser Console (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd>)
 3. Install MTH.
 4. Click the browser action

## Expected result

When functioning properly, MTH shouldn't increase the number of error messages seen in the console.

## Actual result

Depending on the browser setup, I've observed MTH producing "Error: Could not establish connection. Receiving end does not exist." log entries from three different locations so far, when their failure doesn't visibly impede the extension's function:

* Sending `kTSTAPI_CONTEXT_MENU_REMOVE_ALL` on line 74 in `background/context-menu.js`
* Sending `kTSTAPI_CONTEXT_MENU_REMOVE_ALL` and `kTSTAPI_UNREGISTER_SELF` on lines 397 and 400 in `background/background.js`.
* Sending `kCOMMAND_PUSH_SELECTION_INFO` on line 88 in `common/commands.js`.

## Environment

 * Platform (OS): Kubuntu Linux 14.04 LTS
 * Version of Firefox: Developer Edition 62.0b9 (64-bit)
 * Version (or revision) of Multiple Tab Handler: 2.0.13

**Comment by piroor** [comment]
I've added new option `enableIntegrationWithTST`. You can disable it via Debug mode of MTH. For more backgrounds, see my article: https://piro.sakura.ne.jp/latest/blosxom/mozilla/xul/2018-07-28_best-way-to-communicate-we-addons.htm

**Comment by ssokolow** [comment]
I haven't double-checked but I was under the impression that the message could be silenced by adding a `.catch` to the `Promise` returned by `browser.runtime.sendMessage` and that doing so was the proper way to silence such "target extension not found" errors.
