### ISSUE TITLE
Buggy tab llist

### ISSUE THREAD

**Issue by rayman89** [piroor/multipletab#206]
1. When you have more than 20 tabs open in a window the tabs that appear on the multiple tab handler list start repeating themselves. 

2. On top of that if you are selecting multiple tabs and you scroll down to select more, the tabs that you selected above get unselected even if you are holding down control or shift. 
 
3. When you scroll holding a key down like control or shift etc the scrolling gets choppy like its lagging a bit.

All of this was tested on a clean profile with only your addon installed.

![image](https://user-images.githubusercontent.com/5449042/44282671-6b24e280-a221-11e8-949b-f5d6cd9b9eec.png)

![image](https://user-images.githubusercontent.com/5449042/44282793-ca82f280-a221-11e8-8754-cba607186868.png)

![image](https://user-images.githubusercontent.com/5449042/44282777-c0f98a80-a221-11e8-9150-661e265ec320.png)

**Comment by piroor** [comment]
I cannot reproduce this problem on my environment: latest Nightly (63) and a stable release of Firefox (61). Any error message in the browser console or the remote debugger for this addon?

**Comment by rayman89** [comment]
I'm using firefox 62beta on a clean profile. You need to have open more than 20 tabs. 

I enabled debug mode for the addon but IDK how to see the log of your debugger.

This is what the console says

`1534708042898	addons.xpi	WARN	Can't get modified time of x:\FFox.Dev.x64\browser\features\fxmonitor@mozilla.org.xpi
Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:1
Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:7
Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:2
Warning: attempting to write 6460 bytes to preference browser.uiCustomization.state. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
[Show/hide message details.] Warning: unrecognized command line flag -P
nsBrowserContentHandler.js:745
1534708045961	addons.xpi	WARN	Can't get modified time of G:\FFox.Dev.x64\browser\features\fxmonitor@mozilla.org.xpi
Warning: attempting to write 6460 bytes to preference browser.uiCustomization.state. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xul
TypeError: mDragSelection.selection is null
drag-selection.js:393:1
Warning: attempting to write 6460 bytes to preference browser.uiCustomization.state. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.`

**Comment by E3V3A** [comment]
I have the same problem and it occurs with only a few tabs selected. 
In addition, when selecting copy URL to clipboard, there is nothing copied to clipboard!

I'm on Win + `FF 60.1.0esr (64-bit)`

**Comment by rayman89** [comment]
@E3V3A To copy url to the clipboard you need to give the addon extra permissions on the options first.

**Comment by rayman89** [comment]
@piroor Did the new info help?

**Comment by rayman89** [comment]
@piroor True the new version seems to have fixed all the reported issues. Sorry I did not know the new version was supposed to do that. Thank you again.

**Comment by E3V3A** [comment]
yep, now it works
thx
