### ISSUE TITLE
Context menu isn't displayed.

### ISSUE THREAD

**Issue by Kagome-0** [piroor/multipletab#207]
I'm Japanese.
Sorry, My English is very poor and it will annoy you.

## Short description
Multiple Tab Handler versions 2.1 or later don't display context menu.

## Steps to reproduce
1. Clean-install Firefox 61.0.2 x64.
2. Start Firefox with clean profile.
3. Install Multiple Tab Handler.
4. Select any tab(s) on Multiple Tab Handler and right-click but there is no response.
5. Install Tree Style Tab and open it to side panel.
6. Select any tab(s) on Tree Style Tabs.
7. Multiple Tab Handler can be operated temporarily.

## Expected result
Context menu to operate a tab is displayed.

## Actual result
Context menu to operate a tab isn't displayed.

## Environment

 * Platform (OS): Windows 7 SP1 x64
 * Version of Firefox: 61.0.2 x64
 * Version (or revision) of Multiple Tab Handler: 2.1.1

**Comment by piroor** [comment]
Thanks! I've confirmed this problem on the selection panel (not on the sidebar), but the commit 0e9a2d2 should fix this problem.

**Comment by Kagome-0** [comment]
I updated Multiple Tab Handler to version 2.1.2 and confirmed its behaviour.
There is probably no problem.

Thank you for your support!
