### ISSUE TITLE
Not able to activate "Copy URL to clip board"

### ISSUE THREAD

**Issue by E3V3A** [piroor/multipletab#211]
Under the `Extensions` settings I'm trying to activate the copy all tabs URL's to the clip board. 

![firefox_2018-08-25_19-21-33](https://user-images.githubusercontent.com/194392/44620403-203f4680-a883-11e8-9cce-960dd88828d6.png)

But then I get this message:

![2018-08-25_19-21-55](https://user-images.githubusercontent.com/194392/44620402-1fa6b000-a883-11e8-9e6e-08b15cd09a16.png)

I can not find any such toolbar button. Where is it?
(Or is this no longer possible?)

---
My system is:
Windows + `FF 60.1.0esr` (64-bit)
(Was working perfectly under 32 bit FF 52.9.0 ESR!)

This may be related to #193...

**Comment by E3V3A** [comment]
OK, This is weird. Suddenly that icon popped up! But, I've been using the new browser for some time already, but only now that toolbar appeared... 

---

![firefox_2018-08-25_19-50-24](https://user-images.githubusercontent.com/194392/44620633-49fa6c80-a887-11e8-83fc-60586edeb97e.png)

---

![firefox_2018-08-25_19-49-59](https://user-images.githubusercontent.com/194392/44620632-4961d600-a887-11e8-8b2d-14f16ba97f5b.png)


Maybe add these pictures to the Repo Readme?

**Comment by piroor** [comment]
After the commit b624f0b48789442332a3230397ca112a63d6d67c the checkbox in the options dialog should show the permission prompt directly if it is possible,

**Comment by AnselmD** [comment]
I am not able to use "copy to clipboard"
In Extensions-> General -> Extra Permissions of commands  there is no "copy to clipboard"
only a "Bookmark tabs" checkbox.
Unchecking/Checking "Bookmark tabs" and it is asking for additional permissions as expected.
But i can not do this for "copy to clipboard"

**Comment by piroor** [comment]
Which version of Firefox do you use? Now MTH's latest released version supports only Friefox 64 and later, and "Copy to Clipboard" feature is seaprated to a different addon [Copy Selected Tabs to Clipboard](https://addons.mozilla.org/firefox/addon/copy-selected-tabs-to-clipboar/). Sorry but I'm not active to maintain an old version of MTH for Firefox ESR60, and with many reasons I recommend you to use latest released version of Firefox.
