### ISSUE TITLE
Context menu not added to Tree Style Tab when "Open menu automatically after tabs are selected" is unchecked.

### ISSUE THREAD

**Issue by Lej77** [piroor/multipletab#212]
## Short description
When the option `Open menu automatically after tabs are selected` is unchecked the `Selected Tabs`
context menu won't be added to Tree Style Tab's fake context menu after tabs are selected using long press and then drag.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install MTH.
 3. Install TST.
 4. Go to MTH's option page and uncheck the option `Open menu automatically after tabs are selected`.
 5. Long press a tab in Tree Style Tab's sidebar and then drag the mouse over a couple of tabs to select them.
 6. Right click in Tree Style Tab's sidebar to open its fake context menu.

## Expected result
There should be a context menu item with the name `Selected Tabs`.

## Actual result
There isn't a context menu item with the name `Selected Tabs`.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 61.0.2
 * Version (or revision) of Multiple Tab Handler: 2.1.3

**Comment by piroor** [comment]
Thanks! The commit c206057 should fix this.
