### ISSUE TITLE
Changes to the list of "Copy to Clipboard" formats don't get saved

### ISSUE THREAD

**Issue by ssokolow** [piroor/multipletab#213]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install MTH.
 3. Grant "Copy to Clipboard" permissions
 4. Attempt to add a new format to Copy to Clipboard's submenu

## Expected result

The items should appear in the Copy to Clipboard submenu.

## Actual result

The submenu remains unchanged and the changes in the Preferences page may or may not have reverted themselves.

I was forced to enable debug mode and manually edit the contents of `copyToClipboardFormats` to get the changes to stick.

Here is the setup I wound up with:

```json
[{"label":"URI","format":"%URL%"},{"label":"Title and URI","format":"%TITLE%%EOL%%URL%"},{"label":"HTML Link","format":"<a title=\"%TITLE_HTML%\" href=\"%URL_HTML%\">%TITLE_HTML%</a>"},{"label":"Markdown","format":"[%TITLE%](%URL% \"%TITLE%\")"},{"label":"Markdown (List)","format":"%TST_INDENT(  )%* [%TITLE%](%URL% \"%TITLE%\")"},{"label":"TiddlyWiki","format":"[[%TITLE%|%URL%]]"},{"label":"TiddlyWiki (List)","format":"%TST_INDENT(*)%* [[%TITLE%|%URL%]]"},{"label":"reStructuredText (List)","format":"%TST_INDENT(  )%-  `%TITLE% <%URL%>`__"}]
```

I added the "reStructuredText" option this time. "TiddlyWiki" and "TiddlyWiki (List)" were already there from the changes I made when I first installed Multiple Tab Handler.

The problem manifested in both of these test cases:

1. Attempting to add the "reStructuredText" line below "TiddlyWiki (List)" on my day-to-day Firefox Developer Edition profile.
2. Attempting to add the "TiddlyWiki" line below "Markdown (List)" on a brand new install of MTH in a fresh Firefox Nightly profile.

## Environment

 * Platform (OS): Kubuntu 14.04.5 LTS
 * Version of Firefox: 63.0b4 (64-bit) or 64.0a1 (2018-09-12) (64-bit)
 * Version (or revision) of Multiple Tab Handler: 2.1.4.

**Comment by vonHabsi** [comment]
Same here.

It is a good thing I found this issue, I will be able to add Asciidoctor too

**Comment by piroor** [comment]
Thanks! The commit c0596d9 should fix this problem.

**Comment by vonHabsi** [comment]
I have checked this one as well and it is working fine.

Thanks again.
