### ISSUE TITLE
Multiple files with same name with "Save Tabs as Files"

### ISSUE THREAD

**Issue by tobbez** [piroor/multipletab#214]
## Short description
In some cases, when using the 'Save Tabs as Files' feature on multiple tabs that contain files with the same base name, MTH will try to download them to the same local path.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install MTH.
 3. Open two tabs with URLs that have the same base name, for example `example.com/directory1/file.jpg` and `example.com/directory2/file.jpg`.
 4. Make sure your `Saved Tabs` directory doesn't already have a file with the same name (`file.jpg` in the example).
5. Select both the tabs using MTH and invoke the 'Save Tabs as Files' action.

## Expected result
MTH attempts to download both files into the same local path (`file.jpg` in the example).

## Actual result
MTH should download the files into separate paths (`file.jpg` and `file(1).jpg` in the example).

Note that the problem does not seem to occur if a file of the same name already exists before you invoke the action (in that case, the files correctly get (1), (2), ... added to the file names).

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 63.0b4 
 * Version (or revision) of Multiple Tab Handler: 2.1.4

**Comment by tobbez** [comment]
After looking a bit at it, there doesn't seem to be much code in MTH concering downloads (basically just a call to [browser.downloads.download](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download)), so maybe this is a bug in Firefox?

Even if that is the case though, it might be mitigated by waiting until the promise returned by `browser.downloads.download`) resolves before calling `browser.downloads.download` for the next file.

**Comment by piroor** [comment]
Thanks. By the commit 82cc1e4 now downloaded files will have unique name.
