### ISSUE TITLE
Doesn't work at all on FF 57

### ISSUE THREAD

**Issue by rpglover64** [piroor/multipletab#216]
## Short description

Doesn't work at all: clicking on the icon doesn't open a menu, long click on a tab doesn't select it, ctrl-click doesn't select it.

## Steps to reproduce

 1. Start Firefox (57.0.1 (64-bit) on Debian Linux) with clean profile.
 2. Install MTH (from https://addons.mozilla.org/en-US/firefox/addon/multiple-tab-handler/).
 3. Click on the icon

## Expected result

Get a menu

## Actual result

Get no menu

## Environment

 * Platform (OS): Debian Linux
 * Version of Firefox:  57.0.1 (64-bit)
 * Version (or revision) of Multiple Tab Handler: 2.1.4

There's probably something wrong with my machine, but I have no idea how to start debugging it.

**Comment by piroor** [comment]
Sorry, MTH is now actually works only on Firefox 60 or later because it uses ES modules feature and it is supported on Firefox 60 or later. I forgot to update the minimum version information.

**Comment by rpglover64** [comment]
Thanks. Should I close the issue, or do you want to leave it open until you update the info?

**Comment by piroor** [comment]
I've updated supported version information on mozilla.addons.org, so I close this. Thanks!
