### ISSUE TITLE
Support for containers [feature request]

### ISSUE THREAD

**Issue by neekt** [piroor/multipletab#219]
Hi there, 

I have a feature request. I've been looking for an extension that would allow me to select multiple tabs and then move them all to a specified container in Firefox. I haven't found anything that does this yet, and it would seem to fit in perfectly with this extension.

It could be functionally similar to the "Reopen in Container" option that appears when you right click on a tab (only when privacy.userContext.enabled is set to true in about:config), but for multiple tabs instead of just one. The Context Plus extension - https://addons.mozilla.org/en-US/firefox/addon/context-plus/ - has a similar tab context menu option for moving individual tabs to new containers.

Thanks for maintaining a great extension!

**Comment by piroor** [comment]
Please wait for Firefox 64. On Firefox 64 and later context menu on Multiple Tab Handler's panel become compatoble to other tab related addons, and Context Plus's "Move to Context" menu appears in the menu. ([technical details](https://piro.sakura.ne.jp/latest/blosxom/mozilla/xul/2018-10-14_override-context-on-fx64.htm#topic2018-10-14_override-context-on-fx64))

**Comment by piroor** [comment]
Outdated.
