### ISSUE TITLE
Dragging tab-close button results in its selection, tab close

### ISSUE THREAD

**Issue by ferongr** [piroor/multipletab#22]
Similar like issue #20.

Reproduce steps:
1. Click (LMB down) on tab-close button
2. Drag mouse outside outside the button
3. Release mouse button

Expected result: Nothing happens (tab doesn't close)

Actual result: Tab-close button gains blue overlay, tab closes.

![](http://ompldr.org/vYXF2Yg/button.png)

Re-used screenshot from issue #20 since the same exact thing happens.

**Comment by ryancu7** [comment]
I came here to report this bug and see it has already been reported. Hopefully it can be fixed soon. I get trapped by this all the time.

**Comment by piroor** [comment]
This is not a bug but a designed behavior. MTH provides ability to close multiple tabs at once by dragging on clsoeboxes of tabs.
However, as you said this feature is possibly annoying. So I think that selection of closeboxes should be started after the second closebox is selected.

**Comment by ryancu7** [comment]
Ah, I see. Thanks for the reply. I think your idea will work well.

**Comment by piroor** [comment]
The commit 3fd497a6dd666a383f0ad6a819025cb8612408bb introduces this behavior. You can try it with the latest development build: http://piro.sakura.ne.jp/xul/xpi/nightly/
