### ISSUE TITLE
Select and scroll

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/multipletab#225]
Firefox 64, Windows 1803, Multiple Tab Handler 3.0.1
_______________________

## Short description
Limited to drag and select only the length of the visible dropdown/sidebar menu items

Before I install Tree Style tabs, I'd like to know if it will be possible to drag, select, and then scroll as you are selecting, instead of it stopping at the last visible tab.  Also, is shift+click to select a block of tabs available for the dropdown/sidebar menu as it is on the tab bar.

**Comment by piroor** [comment]
Thanks, I forgot to implement that. The commit 87ceced should fix this.
