### ISSUE TITLE
Selection state is lost when closing a tab from the TST sidebar

### ISSUE THREAD

**Issue by joshgold22** [piroor/multipletab#226]
## Short description

If several tabs are selected, and you close a tab using the "x" in the MST sidebar, the selection state is lost.  This does not happen if you close using the "x" on the tab in the built-in Firefox tab bar at the top (I have both visible.)

It's often the case that I want to go through tabs, copy a subset to the clipboard, and close some others.  If I close one in the middle of that process, I have to start over selecting the ones I want to copy.

## Steps to reproduce

1. Select 3 tabs
2. close one using the x on the Tree-style Tabs tab bar

## Expected result

one tab closed, others unaffected, including being selected if they were before

## Actual result

only the active tab is selected

## Environment

 * Platform (OS): OSX 10.12
 * Version of Firefox: 69.0.2
 * Version (or revision) of Multiple Tab Handler: 3.0.10 (2019.8.8) / TST 3.1.8 (2019.9.13)

**Comment by piroor** [comment]
> close one using the x on the Tree-style Tabs tab bar

Does this mean that you close a non-highlighted tab? Then the problem should be fixed with recent commits. Could you try the [development build](https://piro.sakura.ne.jp/xul/xpi/nightly/multipletab-we.xpi) via `about:debugging`?
