### ISSUE TITLE
Command-click does not unselect after Invert selection

### ISSUE THREAD

**Issue by joshgold22** [piroor/multipletab#227]
Command click (on mac, control-click on others) should toggle tab selection, but it only selects.  It does not unselect a tab that was selected.

## Environment

*    Platform (OS): OSX 10.12
*   Version of Firefox: 69.0.2
*  Version (or revision) of Multiple Tab Handler: 3.0.10 (2019.8.8) / TST 3.1.8 (2019.9.13)

**Comment by joshgold22** [comment]
I learned more about this.  In typical circumstances, command click *does* properly unselect the selected tab.  The problem occurs after Invert selection.  If you select some tabs, Invert selection, and *then* command click a tab, it undoes the invert selection, going back to what was selected before (and has no special effect on the tab you command-clicked)

**Comment by piroor** [comment]
Thanks! I forgot to handle the command key. With recent commits command-click looks to toggle selection state in the popup panel for me. Could you try [the development build](https://piro.sakura.ne.jp/xul/xpi/nightly/multipletab-we.xpi) with the `about:debugging`?
