### ISSUE TITLE
Checkboxes don't work

### ISSUE THREAD

**Issue by pmorch** [piroor/multipletab#228]
## Short description

The checkboxes are there to select tabs. If I click on the first two checkboxes, they get checked. But clicking on the Nth one unchecks all checkboxes. I expected that to check the Nth checkbox too...

## Steps to reproduce

 1. Open the menu and start clicking checkboxes
 2. Notice that eventually clicking on a checkbox will cause other unrelated checkboxes to change state.

Here is a [screengrab video](https://youtu.be/hKIOaw3BbOE) showing the problem where clicking on the 3rd checkbox clears all the previous ones. It seems to happen randomly - here on the third tab.

## Expected result

Checkboxes work "normally"

## Actual result

Checkboxes work "abnormally"

## Environment

 * Platform (OS): Ubuntu Linux 18.04 running XFCE.
 * Version of Firefox: 71.0
 * Version (or revision) of Multiple Tab Handler: 3.0.10 (from today)

The screengrab video was recorded from a brand new empty profile.

**Comment by piroor** [comment]
MTH starts selection of tabs by dragging, and it clears existing selection. I think you aimed to click a checkbox but MTH actually detected the operation as a drag-start. This may happen frequently because MTH looks too sensitive for dragstart action. Hmm...

**Comment by piroor** [comment]
After changes a91b330 and 9b26863 now the checkbox area become indraggable. Moreover, 
the actual height of the checkbox is expanded enough to fill the item itself and blank area above/below a checkbox are also treated as the part of the checkbox.

**Comment by pmorch** [comment]
I can confirm that it now works. Thanks!
