### ISSUE TITLE
"And Click Here to Choose Action" doesn't work

### ISSUE THREAD

**Issue by pmorch** [piroor/multipletab#230]
## Short description

The "And Click Here to Choose Action" area doesn't work as I expect.

## Steps to reproduce

 1. Select a tab or two
 2. Click on "And Click Here to Choose Action"

## Expected result

Something happens

However, right-clicking on one of the selected tabs shows a menu that seems to work. I was expecting that menu to also be shown when I click on "And Click Here to Choose Action"

## Actual result

Nothing happens

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 73.0.1
 * Version (or revision) of Multiple Tab Handler: 3.1.2

**Comment by piroor** [comment]
Thanks, this should be fixed with the commit 1445c1a.
