### ISSUE TITLE
Feature request: Move to -> Other window

### ISSUE THREAD

**Issue by joshgold22** [piroor/multipletab#232]
#55  Short description

In the Move To menu, the options are Move to Start, End, and New Window.  It would be useful to add a submenu, Other Window that would contain the other existing windows.  I think it would be sufficiently useful to just place the tabs at the end of the other window.  (For more flexibility, the moved tabs could be selected after the move, to support dragging them, including adding or removing tabs from the selection.)

Windows could be identified by the title of the currently active tab.

**Comment by piroor** [comment]
I've found an addon "Tab Mover" provides the feature:
https://addons.mozilla.org/firefox/addon/tab-mover/
It looks compatible with this addon MTH.

Today MTH just provides an UI to select tabs by dragging, and other commands for selected tabs are separated to independent addons:

* [Save Selected Tabs to Files](https://addons.mozilla.org/firefox/addon/save-selected-tabs-to-files/)
* [Copy Selected Tabs to Clipboard](https://addons.mozilla.org/firefox/addon/copy-selected-tabs-to-clipboar/)

So, sorry but I won't integrate the feature to MTH.

**Comment by joshgold22** [comment]
I'm just confirming that Tab Mover works great with MTH.  Thanks!
