### ISSUE TITLE
Incompatibility with hidden tabs from addons like Simple Tab Groups

### ISSUE THREAD

**Issue by byblo** [piroor/multipletab#235]
Selecting multiple tabs in TST while using other addons that hidden tabs, like Simple Tab Groups addon, results in unwanted selection of tabs hiddens in other STG groups (depending the order of the tabs in the background)

For instance, after a selection, if user choose to mute/unmute, or delete the tabs, the order will also apply to the hidden tabs from other groups.

Please prevent the selection on hidden tabs, or even better : remove/ignore automatically from MTH's list the hidden tabs (maybe optional?)

**Comment by piroor** [comment]
Thanks! I completely forgot to ignore hidden tabs on this addon... The problem should be fixed with recent commits.
