### ISSUE TITLE
Long Press Dragging and Simple Tab Group (or simply hidden tabs) incompatibility

### ISSUE THREAD

**Issue by byblo** [piroor/multipletab#236]
Since the new version of MTH, there is no more hidden tabs selected (thank you!), but this seems to have introduced a new problem:

To reproduce bug:
-----------------------
- Need to get Installed current versions of: Simple Tab Group extension and Mutiple Tab handler (and TST of course)

- Create group A with STG
- Create group B with STG

- goto to group A, create a new tab (google.com, or whatever)
- goto to group B, create a new tab (google.com, or whatever)
- goto to group A, create a new tab (google.com, or whatever)
- goto to group B, create a new tab (google.com, or whatever)
- ect... until you get at least 3 or 4 tab per group

- Now select any of the group, A or B, then try MTH's long press dragging to select all of them, you should see some of them are ignored during the dragging (and maybe even selected later once reached the other extremity)

Please note (a bit offtopic) : This reported bug is not really critical, but I feel STG and TST are not liking each other, and thus got some more incompatibilites, like restoring a closed tab in a wrong tree place and sometimes "randomly" breaking some trees from groups in background while working on a current group, but will create another issue topic about this on TST's issue forum a bit later once I find a way to reproduce those problems each time. This note was just to let you know already that you may want to try to confront each other already.

**Comment by piroor** [comment]
Thank you for the report, I've introduced a fix with the commit e39d36d.

**Comment by piroor** [comment]
Per-problem reports are very helpful for me to track state of them! Please don't mind to create numbers of issues 😃

**Comment by byblo** [comment]
It is working well now here too.

Thank you :)
