### ISSUE TITLE
manually creating group tabs

### ISSUE THREAD

**Issue by bczucz** [piroor/multipletab#239]
Is it possible that the option for generating new group tabs has disappeared? I used to use it, but I cannot find it any more... :( 
I cannot find it in the context menu, nor the tickbox in the options where I could enable this function for the context menu.

Sorry if I missed something obvious.
Balint

 * Platform (OS): Win 10
 * Version of Firefox: 82.0.3 (64-bit)
 * Version (or revision) of Multiple Tab Handler: 3.1.9 (2020.9.29)

**Comment by piroor** [comment]
If you use Tree Style Tab with MTH, It was a part of TST and removed from TST 3.6.0. Now it is separated to a helper addon [TST More Tree Commands](https://addons.mozilla.org/firefox/addon/tst-more-tree-commands/). Please see also: https://github.com/piroor/treestyletab/issues/2756

**Comment by bczucz** [comment]
Yes, this was my use case. I see now what happened. Thanks for your response!
Balint
