### ISSUE TITLE
Wrong select behavior with tabs tree (Tree Style Tab)

### ISSUE THREAD

**Issue by Infocatcher** [piroor/multipletab#31]
Illustration:

<pre>
[ Tab 1 ]           – first selected tab
  [ Tab 2 ]         – second selected tab
   |[ Tab 3 ]       – then move out from tabs (but still over tab bar)
   |  [ Tab 4 ]
   |    [ Tab 5 ]
   |      [ Tab 6 ] - move over last tab (Ok), then move over previous (5'th) tab
   ---------^</pre>

In result first selection range disappears.

**Comment by piroor** [comment]
Outdated.
