### ISSUE TITLE
Save selected to files don't work when path is too long or page not refreshed or something else

### ISSUE THREAD

**Issue by graad** [piroor/multipletab#35]
This may work for issues #23 and #34
My add-on version 0.7.2012111301
Using Firefox 18 beta:
## Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0

I've selected 12 tabs and option "Save Selected Tabs in Archive as..".
Next, tabs where refreshed - probably automatically.
Next, I've selected 12 tabs and option "Save Selected fabs in files..".
which allowed 2 tabs at first.

When I've selected every tab one by one and assured that all were refreshed,
almost all tabs were saved.
The unsaved tabs addresses are:
{1} http://lgforum.pl/viewforum.php?f=29&sid=75427178be9481da60b52f18f9a5e6d4
{2} http://lgforum.pl/viewtopic.php?f=5&t=1806
At the moment, I'm not logged a that lgforum.pl forum.

When saved {1} tab, Error Console shows (all my add-ons where enabled)

Timestamp: 2012-12-18 12:04:32
Error: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIFile.create]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: chrome://maf/content/collecting/persistResourceObject.js :: <TOP_LEVEL> :: line 129"  data: no]
Source File: chrome://maf/content/saving/jobObject.js
Line: 361

When I disabled ALL add-ons(Safe Mode), I might found error source.

When saving pages {1} and {2}:
In original firefox 'Save Page As..' dialog, name of file,
derived probably from webpage title, is too long along with my system path, where I'm saving.
Also, file path for saved webpage files in webpage folder may be too long.
I would think people suffer from this error for long years, and mozilla's firefox don't have option
to automatically found and parse file paths(as long as they are on saving) and shorten file names  or web folder name at least.

Propositions:
- I would love to see your add-on to shortening website name to some sensible number of characters,
  like 30.
- All saved tabs should be refreshed like one would do this by hand, one by one. Its the only way for saving to work?

**Comment by Damienbarifon** [comment]
Try to long path tool. It is very helpful.

**Comment by Davehuu** [comment]
I have the same issue when installing Chrome extensions. They fail with the note Path too long. Then google it and got Long Path Tool. This tool is resolve the issues.

**Comment by piroor** [comment]
Outdated.

**Comment by annalopezz** [comment]
I recommend using the Long Path Tool to resolve this issue.
