### ISSUE TITLE
Conflicts with Tab Mix Plus

### ISSUE THREAD

**Issue by mtd2f** [piroor/multipletab#49]
Conflicts with Tab Mix Plus.
I can't tune extensions up to use both of them.
I would like to:
- Ctrl + left click - to open a copy of a tab (I did it using Tab Mix plus - all is ok)
- Alt + left click (or Shift + left click) - to select tabs (using Multiple Tab Handler - can't obtain it)

**Comment by rayman89** [comment]
You can change the config so they dont conflic with each other. On MTH options go to  General and put "select tabs" on the option that ask you what to do with shift click and leave the control click on "firefox's default" option and it will work like you want although if you do this you cannot use the MHT feature to unselect tabs one by one.For example if you want to select tabs 1 to 6 but not 4  can use control-click on 4 to unselect. If you insist on having control click to duplicate tabs you'll have to re-arrange tabs in order for you to have all the desired tabs nex to each other so you can only use shift.
IMO you might want to change the control click config of TMP to do that with an other key, alt for example, or just add "duplicate tab" to the tab menu (you can do that on TMP's options). That way you can enable the select tab option on MTH without having conflicts with TMP.

**Comment by piroor** [comment]
Outdated.
