### ISSUE TITLE
Need to suppot getShortcutOrURIAndPostData()

### ISSUE THREAD

**Issue by saneyuki** [piroor/multipletab#50]
In Firefox 25,  `getShortcutOrURI()` was removed and it was updated to `getShortcutOrURIAndPostData()`: [Bug 846635 - Use asynchronous getCharsetForURI in getShortcutOrURI](https://bugzilla.mozilla.org/show_bug.cgi?id=846635).

We need to update our code bases.

**Comment by piroor** [comment]
Currently MTH don't use  `getShortcutOrURI()` so I think this issue can be closed.

**Comment by piroor** [comment]
Outdated.
