### ISSUE TITLE
Show warn dialogs if the number of closed tabs is greater than browser.sessionstore.max_tabs_undo

### ISSUE THREAD

**Issue by saneyuki** [piroor/multipletab#59]
I think we should follow [Bug 896291 - 'Close other tabs' should show the confirmation dialog if the number of tabs is greater than browser.sessionstore.max_tabs_undo](http://hg.mozilla.org/mozilla-central/rev/1dd4cd4890fc).
- http://hg.mozilla.org/mozilla-central/file/a475f94bb1b1/browser/base/content/tabbrowser.xml#l1754
- http://hg.mozilla.org/mozilla-central/file/a475f94bb1b1/browser/base/content/tabbrowser.xml#l1657

**Comment by piroor** [comment]
Done by bebd0a16390ca1aa433ae8c628034826e900d822, thanks!
