### ISSUE TITLE
Selected tabs reloaded when moved to another window

### ISSUE THREAD

**Issue by dslijepcevic** [piroor/multipletab#61]
Firefox 13+ has "Don't load tabs until selected" option for loading tabs on demand, which is enabled by default. It only loads a tab from previous session when you click on it. However, this does not seem to work correctly with Multiple Tab Handler add-on when you move selected tabs to another window – they all get fully loaded first. When doing this with many tabs, it will most definetely crash Firefox. Is there a way around it, to defer loading of these tabs until clicked? Thanks.

**Comment by piroor** [comment]
Same to #83 so I close this to shrink the list of opened issues...
