### ISSUE TITLE
Move to new window and suspended tabs

### ISSUE THREAD

**Issue by rayman89** [piroor/multipletab#83]
Move to new window will load all the suspended tabs you have before moving it. It would be nice if it's possible to just move them and not pre-load them before doing so.

**Comment by unknown--** [comment]
I agree. This extension makes thing so much easier for me but this is the only nagging issue that I have.

**Comment by piroor** [comment]
Sadly it can't be done, because Firefox itself always restores swapped tabs even it they are pending.
http://mxr.mozilla.org/mozilla-central/source/browser/base/content/tabbrowser.xml#2412
http://mxr.mozilla.org/mozilla-central/source/browser/components/sessionstore/SessionStore.jsm#1608

**Comment by grahamperrin** [comment]
Whilst it may be impossible to avoid the load of selected tabs, around move time, an extension such as this can help to subsequently reduce the overall load: 

- [Auto Unload Tab](https://addons.mozilla.org/addon/auto-unload-tab/)
