### ISSUE TITLE
not properly working on firefox 36

### ISSUE THREAD

**Issue by thaliel** [piroor/multipletab#85]
When I have opened more than a certain number of tabs with snaplinks plus, Multiple tab handler will not be ablot to select these tabs. Only the active will be selected and moving the mouse pointer over other tabs will not select them as it should. If I reduce the number of open tabs or only open a few tabs, it works perfectly fine. I cannot really tell what the maximum number is, but the addon should be working regardless of the numer of tabs opened.

**Comment by thaliel** [comment]
nevermind, it is working now

**Comment by thaliel** [comment]
and it stopped working again, I have no idea what the problem is

**Comment by piroor** [comment]
Maybe fixed by f90a88651f684917dafe83742ff74a99d0b9c151

**Comment by thaliel** [comment]
I do not now what I am supposed to do with that code

**Comment by piroor** [comment]
You can try the development build from the latest source via http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by thaliel** [comment]
that works perfect, thank you

**Comment by kevinmcfarlane** [comment]
Nightly works for me too. :)
