### ISSUE TITLE
Drag and drop multiple selected tabs to empty space does not move them all to the new window after Firefox 38+

### ISSUE THREAD

**Issue by Rikk** [piroor/multipletab#88]
Drag and drop to move multiple selected tabs to another window doesn't work with Firefox 38.0.
However, a single selected window can be moved normally. Also, menu "Move to new window" is working.

*Updated to note it also happens in v38 final/candidates*

**Comment by rayman89** [comment]
Have you selected on the options in the general tab "Move and reorganize tabs" ? are you using the lastest dev version? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by Rikk** [comment]
It fails if I use either "Default (Move and rearrange tabs)" or "Select tabs", I always used the latter.
Surely, it is caused by something Firefox 38 changed, we need to find what exactly...

**Comment by rayman89** [comment]
If you have the option select tabs then it wont "fail" it will just have an other function. 

I'm just trying to save you some time sin prioor lately is taking a lot of time to do changes and he barely responds. So if you are interested keep reading this else just ignore it.

Are you using the latest version? You did not answer that. 

BTW have you tested it on a clean profile? Have you tested it with different versions of ff 38? Have you tested it on ff 39  and 36?

**Comment by Rikk** [comment]
Yes, I always use latest, have been using for ages, reporting bugs, have made some small patches etc. Since upgrading from 37 to 38beta9 this problem appeared. Have/will not test with previous betas.
Btw, what version do you use? Do you see this problem?

**Comment by rayman89** [comment]
I'm using version 36. But i tested release version on firefox 38.0 and it worked for me. Ill try updating to lastest beta version and i'll also try with latest dev version to see what happens.

**Comment by Rikk** [comment]
Clean profile, same result: only one tab is moved to new window by drag-drop.
What beta of 38 did it work for you? OS?

**Comment by rayman89** [comment]
Im on windows 7x64. 38b9 was the version I used i updated from b1. oh now that i remember im using the x64 version of firefox 38 maybe it's that

ftp://ftp.mozilla.org/pub/mozilla.org/firefox/releases/38.0b9/win64/

you can try it if you want extracting the installer and open the core folder  firefox.exe trough the shortcut with the modified parameters I mentioned on my previous message.

**Comment by Rikk** [comment]
Well, I can reproduce it with every configuration.
38b9 x86 or x64, clean or dirty profiles, Win 8.1 x64 or Win 7 x86.

**Comment by rayman89** [comment]
Wait for him cause I cant' reproduce it.

**Comment by Rikk** [comment]
@piroor 
Still on 40beta.

**Comment by rayman89** [comment]
I see now what's the issue. You are not supposed to drop the selected tabs on the page content else firefox will read it as a vanilla action. Drop the tabs on the tab bar of the desired window on the space you want them to go like this: http://www.imagebam.com/image/24fd53424273120 and it will work

**Comment by Rikk** [comment]
:flushed:
>Drop the tabs on the tab bar of the desired window

Looks so obvious! I could swear I tried it... or maybe not, lol
Thanks!


>You are not supposed to drop the selected tabs on the page content

It used to work before, in that way.
Was it changed in 38?

**Comment by rayman89** [comment]
Cant say for sure could be what you say or maybe that before the add-on overrided that but then it stopped doing so.

**Comment by Rikk** [comment]
Sorry, I was asleep when written above, the bug is with relation to creating new windows from drag drop.
I was comparing same version of MTH (but new Firefox), so it can't have stopped doing whatever it was doing.

**Comment by rayman89** [comment]
*does not move them all to the new window

It does create a new window with the active tab.

**Comment by Rikk** [comment]
Right, that's it. Looks like you reproduced then :smile:

**Comment by rayman89** [comment]
yeah but like i said i think it's just a firefox feature and that the add-on is not supposed to work in that way but if you say that it used to work then it should be reviewed.

**Comment by Rikk** [comment]
Hooray! I think commit https://github.com/piroor/multipletab/commit/9188e5b65620290150a1dd8cf8984df42ded8bf1 fixed this issue!
Thanks!
