### ISSUE TITLE
Tab selection and Australis

### ISSUE THREAD

**Issue by rayman89** [piroor/multipletab#91]
This is a minnor issue but the tab selections is still using the squared tab design. It would be nice if you could make the selction adjust to the "new" tab design.

**Comment by Rikk** [comment]
I know it has already been discussed in another issue opened by you and rejected by author, unless someone provide a pull request...
https://github.com/piroor/multipletab/issues/68#issuecomment-40037304

**Comment by rayman89** [comment]
Sorry I forgot about that.
