### ISSUE TITLE
TypeError: window.messageManager.sendAsyncMessage is not a function

### ISSUE THREAD

**Issue by saneyuki** [piroor/multipletab#93]
## env

- Firefox Nightly 42.0a1
  - build id: 20150723030207
  - https://hg.mozilla.org/mozilla-central/rev/1f77b78797d6
- Multiple Tab Handler v0.8.2015031300a174100

## step to reproduce
1. open a new window 
2. close it

## result

This error is shown in "Browser Console":
`TypeError: window.messageManager.sendAsyncMessage is not a function  view-source:chrome://multipletab/content/multipletab.js:1152:1`

**Comment by piroor** [comment]
Thanks. It was already fixed on other projects... (ex. Tree Style Tab)

**Comment by Rikk** [comment]
#89
