### ISSUE TITLE
not compatible with PaleMoon 25.7.0

### ISSUE THREAD

**Issue by MarvinFS** [piroor/multipletab#95]
was using this awesome plugin for ages in FF, but since FF becoming more and more from a devil's sidem i was forced to migrate to PaleMoon. and multiple tab handler is not working there as expected - even with compatibility disable addon - i'm able to access options and select multiple tabs but can't close them from first attempt... and the number of attempts for making an action is somehow related to a number of selected tabs in browser...  please assist! PaleMoon is a future for firefox i guess!

**Comment by piroor** [comment]
Outdated. MTH now supports only Firefox.
