### ISSUE TITLE
Request: Invert selection and Select similar tabs

### ISSUE THREAD

**Issue by rayman89** [piroor/multipletab#96]
Could you please add Invert selection item menu to the selected tabs menu and Select similar tabs to the normal tab menu and the select tabs menu as well to make selections easier/quicker?

**Comment by piroor** [comment]
The commit 389e1851b4606acea2ab86bc78a7f8e446e2bacc adds them.

**Comment by rayman89** [comment]
Thank a lot piroor you are the man.
