### ISSUE TITLE
Mutiple tab handler breaks Session Restore in Firefox

### ISSUE THREAD

**Issue by Vednier** [piroor/multipletab#99]
Multiple Tab Handler 0.8.2015030601.1-signed on Nightly completely breaks Session Restore and Resume  feature - instead of restoring tabs from previous session (or showing Session restore page) Firefox starts simply creates new, blank one.
Last good Nightly - 07.10.2015, starting from 08.10.2015 its broken. There is error messages in console about error in Multiple Tabs handler too.
Probably cause by this - http://forums.mozillazine.org/viewtopic.php?f=23&t=2966543
https://hacks.mozilla.org/2015/07/es6-in-depth-let-and-const/
A lot of another addons affected by that firefox change too.

**Comment by Rikk** [comment]
I see commit https://github.com/piroor/multipletab/commit/a88cd16757b45961cf4f4a88dbb70f5b80b4b15e from yesterday changed a 'const' to be a 'var', maybe that's the fix you need?
Get updated addon from [here](http://piro.sakura.ne.jp/xul/xpi/nightly/multipletab.xpi).

**Comment by Vednier** [comment]
Yes, this updated build no longer have problem with loading session in Firefox on restart.
